apiVersion: v1
kind: Pod
metadata:
  name: rbd-pv
spec:
  containers:
  - name: rbd
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "60000"]
    volumeMounts:
    - name: rbd-vol
      mountPath: /mnt/rbd-pv
      readOnly: false
  volumes:
  - name: rbd-vol
    persistentVolumeClaim:
      claimName: rbd
