apiVersion: batch/v1
kind: Job
metadata:
  name: busyboxplus
spec:
  completions: 10       //执行job的次数
  parallelism: 1        //执行job的并发数
  template:
    metadata:
      name: busyboxplus
    spec:
      containers:
        - name: busyboxplus
          image: radial/busyboxplus
          imagePullPolicy: IfNotPresent
          command: ["echo", "hello"]
      restartPolicy: Never