apiVersion: v1
kind: Pod
metadata:
  name: pod8-static
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
