apiVersion: batch/v1
kind: Job
metadata:
  name: job2-completion
spec:
  completions: 10
  parallelism: 2 
  template:
    metadata:
      name: busyboxplus
    spec:
      containers:
        - name: ct-busyboxplus
          image: radial/busyboxplus
          imagePullPolicy: IfNotPresent
          command: ["echo", "hello"]
      restartPolicy: Never
